---

- name: Gather information from routers
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Gather Router facts
      cisco.ios.ios_facts:

    - name: Display version information
      ansible.builtin.debug:
        msg: "The IOS version is: {{ ansible_net_version }}"

    - name: Display Serial number
      ansible.builtin.debug:
        msg: "The Serial Number is: {{ ansible_net_serialnum }}"

    - name: Generate CVS report
      delegate_to: qnap
      run_once: true
      copy:
        dest: "./router_info.csv"
        content: |
          hostname,ios_version,serial_number
          {% for host in groups['cisco'] %}
          {{ host }},{{ hostvars[host]['ansible_net_version'] }},{{ hostvars[host]['ansible_net_serialnum'] }}
          {% endfor %}
