---
- name: show interfaces
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Show interfaces
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: Print output
      debug:
        var: output.stdout_lines
