---
- name: Network Clean Up
  hosts: cisco
  gather_facts: no

  vars:
    asn_map:
      R1: 65001
      R2: 65002
      R3: 65003
      R4: 65004

  tasks:

    #PRE-CHECK
    - name: Check current routing config
      cisco.ios.ios_command:
        commands:
          - show running-config | section router
      register: precheck

    - name: Show current config
      debug:
        var: precheck.stdout_lines

    #REMOVE OSPF
    - name: Remove OSPF
      cisco.ios.ios_config:
        lines:
          - no router ospf 1

    #REMOVE BGP
    - name: Remove BGP
      cisco.ios.ios_config:
        lines:
          - no router bgp {{ asn_map[inventory_hostname] }}

    #REMOVE LOOPBACK
    - name: Remove Loopback1
      cisco.ios.ios_config:
        lines:
          - no interface Loopback1

    #POST-CHECK
    - name: Verify cleanup
      cisco.ios.ios_command:
        commands:
          - show running-config | section router
      register: postcheck

    - name: Show after cleanup
      debug:
        var: postcheck.stdout_lines

    #VALIDATION
    - name: Validate cleanup
      assert:
        that:
          - postcheck.stdout[0] == ""
        fail_msg: "Cleanup failed, routing config still exists!"
        success_msg: "Cleanup successful, config removed"