---
- name: Test show command
  hosts: cisco
  gather_facts: no

  collections:
    - cisco.ios

  tasks:
    - name: Show ip interface brief
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: Print output
      debug:
        var: output.stdout_lines