---
- name: Test SSH only
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Run show command
      raw: show ip interface brief
      register: output

    - debug:
        var: output.stdout_lines